### ISSUE TITLE
feat: Support for changing position

### ISSUE THREAD

**Issue by SteveYuOWO** [SteveYuOWO/vue-hot-toast#3]
The current implementation of the Vue Hot Toast library doesn't provide an option to change the position of toast notifications on the screen. It's essential to have a feature that allows custom positioning of toast notifications like top-center, bottom-left, bottom-right, etc., to provide flexibility in how toast notifications are displayed in different application layouts.

TODO: Support for changing position, like `top-center`... etc 6 positions of screen

**Comment by j0rgedev** [comment]
I'll be reviewing this

**Comment by aminnausin** [comment]
Editing the "@steveyuowo/vue-hot-toast/vue-hot-toast.css" file directly from 

`.VueHotToast__toast-container {
  top: 0;
  left: 0;
  width: 100%;
}`

to 

`.VueHotToast__toast-container {
  bottom: 0;
  right: 0;
}`

is the easy fix until an update is released (for bottom right in my case)

**Comment by HarryZ10** [comment]
@SteveYuOWO i cooked today :)

**Comment by HarryZ10** [comment]
@SteveYuOWO
